services:
  comments-mysql-primary-service:
    image: mysql:8.0
    container_name: comments-mysql-primary
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - comments-comments-mysql_data_primary:/var/lib/mysql
      - ./mysql/primary.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the init script
    mem_limit: 1024m   # 限制最大内存为1024MB
    mem_reservation: 512m  # 内存保留值为512MB
    ports:
      - "12306:3306"
    networks:
      - comments-net
    command: --server-id=2 --log-bin=comments-primary-bin

  # comments-mysql-replica-service:
  #   image: mysql:8.0
  #   container_name: comments-mysql-replica
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
      
  #   volumes:
  #     - comments-comments-mysql_data_replica:/var/lib/mysql
  #     - ./mysql/replica.sql:/docker-entrypoint-initdb.d/init.sql
  #   mem_limit: 512m   # 限制最大内存为512MB
  #   mem_reservation: 256m  # 内存保留值为256MB
  #   ports:
  #     - "12307:3306"
  #   networks:
  #     - comments-net
  #   command: --server-id=12 --read-only --log-bin=comments-primary-bin

networks:
  comments-net:
    external: true

volumes:
  comments-comments-mysql_data_primary:
  # comments-comments-mysql_data_replica: