apiVersion: v1
kind: Namespace
metadata:
  name: platform-auth
---
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: platform-auth
spec:
  capacity:
    storage: 4Gi  # 根据需求调整存储大小
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/mysql/primary
  storageClassName: standard
---
metadata:
  name: mysql-pv-replica
  namespace: platform-auth
spec:
  capacity:
    storage: 4Gi  # 根据需求调整存储大小
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/mysql/replica
  storageClassName: standard
