services:
  mysql-primary-service:
    image: mysql:8.0
    container_name: review-mysql-primary
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data_primary:/var/lib/mysql
      - ./mysql/primary.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the init script
    ports:
      - "16306:3306"
    networks:
      - review-net
    command: --server-id=1 --log-bin=primary-bin

  mysql-replica-service:
    image: mysql:8.0
    container_name: review-mysql-replica
    environment:
      MYSQL_ROOT_PASSWORD: root
      
    volumes:
      - mysql_data_replica:/var/lib/mysql
      - ./mysql/replica.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "16307:3306"
    networks:
      - review-net
    command: --server-id=4 --read-only --log-bin=primary-bin

networks:
  review-net:
    external: true

volumes:
  mysql_data_primary:
  mysql_data_replica: