services:
  user-mysql-primary-service:
    image: mysql:8.0
    container_name: user-mysql-primary
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - user-mysql_data_primary:/var/lib/mysql
      - ./mysql/primary.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the init script
    mem_limit: 1024m   # 限制最大内存为1024MB
    mem_reservation: 512m  # 内存保留值为512MB
    ports:
      - "16306:3306"
    networks:
      - user-net
    command: --server-id=6 --log-bin=user-primary-bin

  # user-mysql-replica-service:
  #   image: mysql:8.0
  #   container_name: user-mysql-replica
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
      
  #   volumes:
  #     - user-mysql_data_replica:/var/lib/mysql
  #     - ./mysql/replica.sql:/docker-entrypoint-initdb.d/init.sql
  #   mem_limit: 512m   # 限制最大内存为512MB
  #   mem_reservation: 256m  # 内存保留值为256MB
  #   ports:
  #     - "16307:3306"
  #   networks:
  #     - user-net
  #   command: --server-id=16 --read-only --log-bin=user-primary-bin

networks:
  user-net:
    external: true

volumes:
  user-mysql_data_primary:
  # user-mysql_data_replica: