services:
  mysql-primary-service:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: yuxyuxx
      MYSQL_PASSWORD: yuxyuxx
      MYSQL_DATABASE: db_auth_1
    volumes:
      - mysql_data_primary:/var/lib/mysql
      - ./mysql/primary.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the init script
    ports:
      - "13306:3306"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - envoy_auth-net
    command: --server-id=1 --log-bin=primary-bin

  mysql-replica-service:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data_replica:/var/lib/mysql
      - ./mysql/replica.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "13307:3306"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - envoy_auth-net
    command: --server-id=4 --read-only --log-bin=primary-bin

  redis-primary-service:
    image: redis:latest
    volumes:
      - ./redis/primary.conf:/usr/local/etc/redis/redis.conf
      - redis_data_primary:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "16379:6379"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - envoy_auth-net

  redis-replica-service:
    image: redis:latest
    volumes:
      - ./redis/replica.conf:/usr/local/etc/redis/redis.conf
      - redis_data_replica:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "16380:6379"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - envoy_auth-net

  rabbitmq-service:
    image: yux-rabbitmq:latest
    environment:
      RABBITMQ_CLUSTER_PARTITION_HANDLING: autoheal
      RABBITMQ_NODENAME: rabbit@$(hostname)
    ports:
      - "35673:15672"
      - "35672:5672"
    deploy:
      replicas: 1
      mode: replicated
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: none
    networks:
      - envoy_auth-net
    volumes:
      - ./rabbitmq/rabbitmq_data.config:/etc/rabbitmq/rabbitmq.config"
      - rabbitmq_data:/var/lib/rabbitmq
    command: >
      sh -c "
        rabbitmqctl join_cluster rabbit@rabbitmq-service &&
        rabbitmqctl start_app &&
        tail -f /dev/null
      "

networks:
  envoy_auth-net:
    external: true

volumes:
  mysql_data_primary:
  mysql_data_replica:
  redis_data_primary:
  redis_data_replica:
  rabbitmq_data: