services:
  announcement-mysql-primary-service:
    image: mysql:8.0
    container_name: announcement-mysql-primary
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - announcement-mysql_data_primary:/var/lib/mysql
      - ./mysql/primary.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the init script
    mem_limit: 1024m   # 限制最大内存为1024MB
    mem_reservation: 512m  # 内存保留值为512MB
    ports:
      - "11306:3306"
    networks:
      - announcement-net
    command: --server-id=1 --log-bin=announcement-primary-bin

  # announcement-mysql-replica-service:
  #   image: mysql:8.0
  #   container_name: announcement-mysql-replica
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
      
  #   volumes:
  #     - announcement-mysql_data_replica:/var/lib/mysql
  #     - ./mysql/replica.sql:/docker-entrypoint-initdb.d/init.sql
  #   mem_limit: 512m   # 限制最大内存为512MB
  #   mem_reservation: 256m  # 内存保留值为256MB
  #   ports:
  #     - "11307:3306"
  #   networks:
  #     - announcement-net
  #   command: --server-id=11 --read-only --log-bin=announcement-primary-bin

networks:
  announcement-net:
    external: true

volumes:
  announcement-mysql_data_primary:
  # announcement-mysql_data_replica: