services:
  envoy-service:
    image: envoyproxy/envoy:tools-dev
    ports:
      - "8080:8080"  
    deploy:
      replicas: 1
      restart_policy:
        condition: none
    networks:
      - auth-net
      - user-net
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ./descriptor.pb:/etc/envoy/descriptor.pb
    environment:
      - ENV_HOST=host.docker.internal  # 设置宿主机的域名

networks:
  auth-net:
    driver: overlay
  user-net:
    driver: overlay