admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901

static_resources:
  listeners:
    - name: yux_listen # 监听器名称
      address:
        socket_address:
          address: 0.0.0.0 # 监听所有 IP
          port_value: 8080 # 客户端请求的 REST 端口
      filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: ingress_http
              codec_type: AUTO
              http_filters:
                - name: envoy.filters.http.ext_authz
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
                    grpc_service:
                      google_grpc:
                        target_uri: "172.28.96.1:50009"
                        stat_prefix: "ext_authz"
                    failure_mode_allow: false
                - name: envoy.filters.http.grpc_json_transcoder # 转换过滤器
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_json_transcoder.v3.GrpcJsonTranscoder
                    proto_descriptor: "/etc/envoy/descriptor.pb" # gRPC 描述文件路径
                    services:
                      - "auth.AuthService"
                      - "user.UserService"
                      - "aggregator.AggregatorService"
                    print_options:
                      add_whitespace: true
                      always_print_primitive_fields: true
                - name: envoy.filters.http.router # 路由过滤器
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
              
              route_config:
                virtual_hosts:
                  - name: all_service
                    domains: ["*"] # 匹配所有域名
                    routes:
                      - match:
                          path: '/user.UserService/Register'
                        route:
                          cluster: user_service # 指定 gRPC auth 集群
                        typed_per_filter_config:
                          envoy.filters.http.ext_authz:
                            "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthzPerRoute
                            disabled: true # 禁用外部授权
                      - match:
                          path: "/aggregator.AggregatorService/Login" # 登录 路径
                        route:
                          cluster: aggregator_service # 指定 gRPC auth 集群
                        typed_per_filter_config:
                          envoy.filters.http.ext_authz:
                            "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthzPerRoute
                            disabled: true # 禁用外部授权
  clusters:
    - name: aggregator_service # gRPC 聚合层 服务集群
      connect_timeout: 5s
      lb_policy: ROUND_ROBIN
      type: LOGICAL_DNS
      http2_protocol_options:  # 对于 HTTP/2 配置
        initial_connection_window_size: 1048576  # 初始连接窗口大小
        initial_stream_window_size: 1048576  # 初始流窗口大小
        max_concurrent_streams: 1000
      load_assignment:
        cluster_name: aggregator_service
        endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 172.28.96.1
                    port_value: 50000
      circuit_breakers:
        thresholds:
          - priority: default
            max_connections: 1000
            max_pending_requests: 1000
            max_requests: 1000
            max_retries: 3
      per_connection_buffer_limit_bytes: 32768  # 每个连接的缓冲区限制，单位字节

    - name: user_service # gRPC user 服务集群
      connect_timeout: 5s
      lb_policy: ROUND_ROBIN
      type: LOGICAL_DNS
      http2_protocol_options:  # 对于 HTTP/2 配置
        initial_connection_window_size: 1048576  # 初始连接窗口大小
        initial_stream_window_size: 1048576  # 初始流窗口大小
        max_concurrent_streams: 1000
      load_assignment:
        cluster_name: user_service
        endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 172.28.96.1
                    port_value: 50010
      circuit_breakers:
        thresholds:
          - priority: default
            max_connections: 1000
            max_pending_requests: 1000
            max_requests: 1000
            max_retries: 3
      per_connection_buffer_limit_bytes: 32768  # 每个连接的缓冲区限制，单位字节

    - name: auth_service # gRPC auth 服务集群
      connect_timeout: 5s
      lb_policy: ROUND_ROBIN
      type: LOGICAL_DNS
      http2_protocol_options:  # 对于 HTTP/2 配置
        initial_connection_window_size: 1048576  # 初始连接窗口大小
        initial_stream_window_size: 1048576  # 初始流窗口大小
        max_concurrent_streams: 1000
      load_assignment:
        cluster_name: user_service
        endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 172.28.96.1
                    port_value: 50020
      circuit_breakers:
        thresholds:
          - priority: default
            max_connections: 1000
            max_pending_requests: 1000
            max_requests: 1000
            max_retries: 3
      per_connection_buffer_limit_bytes: 32768  # 每个连接的缓冲区限制，单位字节