services:
  rabbitmq-service:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: yuxyuxx
      RABBITMQ_DEFAULT_PASS: yuxyuxx
    ports:
      - "15672:15672"   # 管理界面
      - "5672:5672"     # AMQP 协议端口
    networks:
      - auth-net
      - user-net
    volumes:
      - data:/var/lib/rabbitmq  # 持久化数据

networks:
  auth-net:
    external: true
  user-net:
    external: true

volumes:
  data: