services:
  redis-primary-service:
    image: redis:latest
    container_name: redis-primary
    environment:
      - REDIS_PASSWORD=yuxyuxx
    volumes:
      - ./primary.conf:/usr/local/etc/redis/redis.conf
      - data_primary:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf","--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "16379:6379"
    networks:
      - auth-net
      - user-net

  redis-replica-service:
    image: redis:latest
    container_name: redis-replica
    environment:
      - REDIS_PASSWORD=yuxyuxx
    volumes:
      - ./replica.conf:/usr/local/etc/redis/redis.conf
      - data_replica:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf","--requirepass", "${REDIS_PASSWORD}", "--masterauth", "${REDIS_PASSWORD}", "--replicaof", "redis-primary-service", "6379"]
    ports:
      - "16380:6379"
    networks:
      - auth-net
      - user-net

networks:
  auth-net:
    external: true
  user-net:
    external: true

volumes:
  data_primary:
  data_replica: